apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: noderollouts.navarchos.pusher.com
spec:
  group: navarchos.pusher.com
  names:
    kind: NodeRollout
    plural: noderollouts
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            nodeNames:
              description: NodeNames allows specific nodes to be requested for replacement
                by name. The priority set on the name will be passed to the NodeReplacement.
                NodeName priorities always override NodeSelector priorities.
              items:
                properties:
                  name:
                    type: string
                  replacement:
                    properties:
                      priority:
                        description: Priority determines the priority of this NodeReplacement.
                          Higher priorities should be replaced sooner.
                        format: int64
                        type: integer
                    type: object
                required:
                - name
                type: object
              type: array
            nodeSelectors:
              description: NodeSelectors uses label selectors to select a group of
                nodes. The priority set on the label selector will be passed to the
                NodeReplacement. The highest priority of any matching LabelSelector
                will be used,
              items:
                properties:
                  matchExpressions:
                    description: matchExpressions is a list of label selector requirements.
                      The requirements are ANDed.
                    items:
                      type: object
                    type: array
                  matchLabels:
                    description: matchLabels is a map of {key,value} pairs. A single
                      {key,value} in the matchLabels map is equivalent to an element
                      of matchExpressions, whose key field is "key", the operator
                      is "In", and the values array contains only "value". The requirements
                      are ANDed.
                    type: object
                  replacement:
                    properties:
                      priority:
                        description: Priority determines the priority of this NodeReplacement.
                          Higher priorities should be replaced sooner.
                        format: int64
                        type: integer
                    type: object
                type: object
              type: array
          type: object
        status:
          properties:
            conditions:
              description: Conditions gives detailed condition information about the
                NodeRollout
              items:
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime of this condition
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: LastUpdateTime of this condition
                    format: date-time
                    type: string
                  message:
                    description: Message associated with this condition
                    type: string
                  reason:
                    description: Reason for the current status of this condition
                    type: string
                  status:
                    description: Status of this condition
                    type: string
                  type:
                    description: Type of this condition
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            phase:
              description: Phase is used to determine which phase of the replacement
                cycle a Rollout is currently in.
              type: string
            replacementsCompleted:
              description: ReplacementsCompleted lists the names of all NodeReplacements
                that have successfully replaced their node.
              items:
                type: string
              type: array
            replacementsCompletedCount:
              description: ReplacementsCompletedCount is the count of ReplacementsCompleted.
                This is used for printing in kubectl.
              format: int64
              type: integer
            replacementsCreated:
              description: ReplacementsCreated lists the names of all NodeReplacements
                created by the controller for this NodeRollout.
              items:
                type: string
              type: array
            replacementsCreatedCount:
              description: ReplacementsCreatedCount is the count of ReplacementsCreated.
                This is used for printing in kubectl.
              format: int64
              type: integer
          required:
          - phase
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
