apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: navarchos 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: navarchos
subjects:
- kind: ServiceAccount
  name: navarchos 
  namespace: kube-system
