apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: navarchos
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: navarchos
subjects:
- kind: ServiceAccount
  name: navarchos 
  namespace: kube-system
