apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: navarchos
  namespace: kube-system
rules:
- apiGroups:
  - "" 
  resources:
  - configmaps
  - events
  verbs:
  - get
  - update
  - patch
  - create
  - delete
